### ISSUE TITLE
rollback method

### ISSUE THREAD

**Issue by vtolstov** [petermattis/pebble#104]
Does pebble needs rollback method i see the most of kv (bbolt, leveldb, badger) have method to discard batch/transaction via rollback/discard, why pebble does not have such method?

**Comment by petermattis** [comment]
Pebble supports a rollback method in the same way that LevelDB and (non-transactional) RocksDB do: don't commit a batch. Note that Pebble, like LevelDB, does not support transactions. It supports atomic batches. Such batches provide atomicity, consistency, and durability, but not isolation. It is up to the user to provide isolation (which admittedly can be quite onerous). Providing full transactional support is not something that will be added to Pebble.

**Comment by vtolstov** [comment]
thanks

**Comment by vtolstov** [comment]
@petermattis sorry, if i use only single writer with many concurrent readers, does it mean that i can guaranties isolation?

**Comment by petermattis** [comment]
@vtolstov The readers would have to read from a snapshot, but doing so should produce serializable isolation.
