### ISSUE TITLE
db: log LSM changes

### ISSUE THREAD

**Issue by ajkr** [petermattis/pebble#113]
Logging the flushes/compactions that are happening can help us understand why the DB stalls.

**Comment by petermattis** [comment]
In general, `Options.Logger` is under-utilized.

For flushes and compactions, I was wondering if providing a default event listener which logs would be useful.

**Comment by petermattis** [comment]
Btw, something I've been wondering: should we add a timestamp to the version edits stored in the `MANIFEST`? If we did that, combined with a parameter to store historical `MANIFESTs`, we could have a precise timestamped record of the evolution of the LSM. I was thinking about this a while back from the perspective of trying to visualize the LSM evolution over time, but it could also be useful for debugging.

**Comment by ajkr** [comment]
> Btw, something I've been wondering: should we add a timestamp to the version edits stored in the MANIFEST? If we did that, combined with a parameter to store historical MANIFESTs, we could have a precise timestamped record of the evolution of the LSM. I was thinking about this a while back from the perspective of trying to visualize the LSM evolution over time, but it could also be useful for debugging.

Yes, that'd be nicer than trying to figure out the LSM state from the logs. Although, writing it to logs requires a few lines of code, while writing it to manifest + writing a tool to interpret it would take a while. So I'll probably just stick with the former for today's purpose.

> For flushes and compactions, I was wondering if providing a default event listener which logs would be useful.

Let me try it. I think so.

**Comment by petermattis** [comment]
> So I'll probably just stick with the former for today's purpose.

Yep, logging is fine in the short term. That suggestion was a thought for the future.

**Comment by petermattis** [comment]
There is now a facility for logging compactions. I don't think this needs to be kept open.
