### ISSUE TITLE
db: sprinkle directory fsyncs where necessary

### ISSUE THREAD

**Issue by petermattis** [petermattis/pebble#125]
Directories need fsyncs just like files. Whenever we manipulate filenames (file creation, or renaming) and expect that operation to survive a crash, we need to fsync the parent directory.

**Comment by petermattis** [comment]
RocksDB fsyncs the sstable dir after flushes, and compactions. It syncs the WAL dir after creation of a new WAL file. And it syncs the WAL dir when "syncing closed logs" (`DBImpl::SyncClosedLogs`). This latter directory sync is curious to me as I don't understand why it is necessary. This behavior arrived in https://github.com/facebook/rocksdb/commit/d5a51d4de3cb71aee0ee4d5578fa9927189fcad2, but I'm still not clear on the need the special need there. Why isn't the normal behavior of syncing the WAL directory upon WAL file creation sufficient?

@ajkr Do you happen to have an insight? Note that this is related to multiple column families, which Pebble doesn't currently support.

**Comment by ajkr** [comment]
That commit is when the bug fixed by https://github.com/cockroachdb/rocksdb/pull/28 was introduced. I recall writing the history of that in some detail. Here it is in our encyclopedia of RocksDB fsync knowledge: https://github.com/cockroachdb/cockroach/issues/34897#issuecomment-481525820.

**Comment by ajkr** [comment]
Oh, that explanation covered why we sync the WAL in that case, not why we sync the WAL directory. I agree the latter seems strange. Maybe it's a mistake (but a harmless one).
