### ISSUE TITLE
cmd/pebble: Add option to wait for background compactions to finish

### ISSUE THREAD

**Issue by ajkr** [petermattis/pebble#137]
After running write-heavy workloads, a variable amount of compaction debt will have accumulated. If we look at the write-amp at that point in time, it doesn't give us a good indication of the total writes necessary to accommodate the workload. Instead, we can wait for compaction debt to clear (i.e., all levels are scored <= 1.0), after which all writes incurred by the workload will have finished.

Ideally we should print write-amp/LSM details both right when the workload finishes and after waiting for compaction debt to clear. The former would tell us the "burst write-amp", while the latter would tell us the "overall write-amp".

**Comment by petermattis** [comment]
I've wanted something like this as well, and hacked in something recently. Let me see about cleaning it up (unless you already have something in progress here).

**Comment by ajkr** [comment]
I hadn't worked on this so feel free to take over.
