### ISSUE TITLE
effective copy val from one key to another

### ISSUE THREAD

**Issue by vtolstov** [petermattis/pebble#149]
If i need copy one key value to another key, does it possible to "offload" this and not read key value? Or only one option is to read full key value and write it to another key?

**Comment by petermattis** [comment]
There is no support for avoiding the copy. Your application could do something by not storing the value under the second key, but instead storing the key where the value is originally stored. At read time, you'll have to have some means of detecting that the value is actually another key and not the value. If the value is small this doesn't make a lot of sense, but if the value is large it does. This would be similar to a symbolic link in a filesystem.

**Comment by vtolstov** [comment]
Thanks, this makes sense.
