### ISSUE TITLE
truncate manifest after sync failure

### ISSUE THREAD

**Issue by ajkr** [petermattis/pebble#153]
We should check whether this bug (https://github.com/facebook/rocksdb/issues/4990) also exists in Pebble and fix it if so.

**Comment by petermattis** [comment]
I'd be willing to bet this affects Pebble too. Is truncating to the previous size sufficient after a sync failure? Seems like we might be unable to perform the truncate at that point. Also, there is a possibility that the process crashes before we get to the truncate, in which case we're in a permanently bad state. My instinct would be to try and deal with this during recovery, doing something more intelligent about the last version edit in the file if it refers to non-existent sstables. Maybe.

**Comment by ajkr** [comment]
Interesting question. I don't know. AFAICT `ftruncate` dirties the inode without syncing so it can work even if a previous sync operation failed. We might not be able to sync the dirty metadata to disk, but that's ok because we weren't able to sync the writes it is truncating either.

Strangely the only source of information I could find on this is a sentence mentioning `ftruncate` in **`fsync`'s** manpage.

Another possible solution is open the file with `O_DSYNC`. Seems the problem is that `write` can succeed while the corresponding `fdatasync` fails.

**Comment by petermattis** [comment]
> Another possible solution is open the manifest with O_DSYNC. Seems the problem can only happen if write succeeds and the corresponding fdatasync fails.

I think this would depend on the behavior of `O_DSYNC`. I can imagine `O_DSYNC` being equivalent to `write`+`fdatasync` internally, which could then have the same failure behavior of separate `write` and `fdatasync` calls. I'd actually be quite surprised if Linux treated `O_DSYNC` as a single atomic operation.

> AFAICT ftruncate dirties the inode without syncing so it can work even if a previous sync operation failed. We might not be able to sync the dirty metadata to disk, but that's ok because we weren't able to sync the writes it is truncating either.

The guarantees around syncing are super vague. This seems quite subtle. Nothing obviously better is springing to mind, but I'm still thinking about this.

**Comment by petermattis** [comment]
Per upstream and offline discussion, crashing the process on MANIFEST sync failure seems the easiest and safest approach. The crash needs to occur before the sstables that were part of the compaction are deleted. During recovery we already write and sync a new MANIFEST. If that fails we'll have to crash again. This crash loop isn't particularly attractive, but sync failure should be super rare, and trying to build in recovery mechanisms that are almost never use seems fraught.
