### ISSUE TITLE
error during recovery: "internal error: level 0 files are not in increasing largest seqNum order"

### ISSUE THREAD

**Issue by ajkr** [petermattis/pebble#161]
Full output:

```
$ ./pebble scan /mnt/data1/db/
dir /mnt/data1/db/
concurrency 1
I190606 04:23:30.356562 1 pebble:1  bad line number: pebble: internal error: level 0 files are not in increasing largest seqNum order: 16011022, 16011022
```

The DB is available at "s3://andrewk-artifacts/eng=pebble.b=64.n=16000000/". It can be downloaded using this command: `aws s3 cp --recursive s3://andrewk-artifacts/eng=pebble.b=64.n=16000000/ <local db dir>`.

Unfortunately I lost the logs from when the DB was generated. AFAIK there was no failure. The command used to generate it looked like this:

```
$ ./pebble ycsb /mnt/data1/db/ --num-ops 16000000 --duration 0 --concurrency 1024 --values 64 --workload scan=0,insert=100 --wait-compactions
```

**Comment by ajkr** [comment]
Here is the output of `ldb manifest_dump`:

```
$ ./ldb manifest_dump --db=/mnt/data1/db/ --hex
--------------- Column family "default"  (ID 0) --------------
log number: 1235
comparator: cockroach_comparator
--- level 0 --- version# 1 ---
 1236:49240342[15146724 .. 15687784]['757365723130303030303131313237383933383230393700' seq:15619748, type:1 .. '757365723939393939363031353736363538363338383500' seq:15314113, type:1]
--- level 1 --- version# 1 ---
...
```

That's weird, where is seqnum 16011022?

```
$ for f in /mnt/data1/db/*log ; do echo $f && ./ldb dump_wal --walfile=$f | grep 16011022 ; done
...
/mnt/data1/db/001226.log
16011022,1,103,37001872,PUT(0) : 0x757365723633303134353530303630343339313538373900
/mnt/data1/db/001235.log
16011022,1,103,36989375,PUT(0) : 0x757365723935323034363437383137333833393337373900
/mnt/data1/db/001238.log
16011022,1,104,36983109,PUT(0) : 0x75736572313131353539323830393835343333393834303400
...
```

The order of fields is "Sequence,Count,ByteSize,Physical Offset,Key(s)". That seems to indicate there is an entry with the same seqnum in three different WALs.

Since I'm using hacky scripts to generate the data, it is very possible I did something wrong like attempt to have multiple writer processes on the same DB. In RocksDB the LOCK file would prevent this but I am not sure about Pebble.

**Comment by petermattis** [comment]
> That's weird, where is seqnum 16011022?

The assertion failure happens before the flush was installed. So you wouldn't expect to see 16011022 in the MANIFEST.

> The order of fields is "Sequence,Count,ByteSize,Physical Offset,Key(s)". That seems to indicate there is an entry with the same seqnum in three different WALs.

That's truly bizarre. And it looks like the seqnum is associated with 3 different batches. 

> Since I'm using hacky scripts to generate the data, it is very possible I did something wrong like attempt to have multiple writer processes on the same DB. In RocksDB the LOCK file would prevent this but I am not sure about Pebble.

Pebble uses the exact same LOCK file mechanism as RocksDB. Possible there is a bug here, but a simple test shows that two `pebble` commands running on the same directory fails. I wonder, though, if `pebble -w` could cause problems. I think the `--wipe` flag doesn't attempt to grab the lock first.

**Comment by ajkr** [comment]
> Pebble uses the exact same LOCK file mechanism as RocksDB. Possible there is a bug here, but a simple test shows that two pebble commands running on the same directory fails. I wonder, though, if pebble -w could cause problems. I think the --wipe flag doesn't attempt to grab the lock first.

Not sure why I didn't think of this yesterday - my scripts might've written multiple DBs to the same S3 directory. It looks like that is the case since the timestamps of the different WALs are hours apart. Sorry for the confusion!

**Comment by petermattis** [comment]
> Not sure why I didn't think of this yesterday - my scripts might've written multiple DBs to the same S3 directory. It looks like that is the case since the timestamps of the different WALs are hours apart. Sorry for the confusion!

Glad it wasn't something more serious. I freaked out a bit this morning when I saw this issue.
