### ISSUE TITLE
Better Examples/Explanations On How To Use Iterator?

### ISSUE THREAD

**Issue by postables** [petermattis/pebble#168]
I'm a little confused on the semantics/usage of the iterator, and couldn't find any concise/clear examples on how it works. I took a look at the iter tests, and they were a bit hard to deduce how exactly to use it.

For the purpose of the follwoing, `db` is a valid opened people datastore.

Lets say I want to search for keys that at a minimum contain the value `kek`, but also keys that contain `keks` `keks2, etc... I'm guessing I would instantiate an iterator like so, and do the following:

```Golang
        iter := db.NewIter(&pebble.IterOptions{LowerBound: []byte("kek")})
	for succ := iter.Next(); succ == true; succ = iter.Next() {
		val := iter.Value()
	}
```

However I can't seem to be able to return any results, not sure what I'm doing wrong.

**Comment by postables** [comment]
Update, I was able to get it working with a pattern like this:

```Golang
	if !iter.First() {
		return nil, errors.New("no results found")
	}
	for {
		if !iter.SeekGE(key) {
			break
		}
		if !iter.Next() {
			break
		}
	}
```

Is it intentional for the iterator system to behave like this? This feels very awkward, and it would be much nicer to have a system that works with the pattern i used in my OP.

For example, `BoltDB/bbolt` works with a pattern like the one in the OP, and it is *much* nicer

```Golang
			for k, v := cursor.First(); k != nil; k, v = cursor.Next() {
			}
```

**Comment by petermattis** [comment]
Hi @postables. I think you've somehow made this more complicated than necessary. Did you try the boltdb approach? The following should work:

```
for valid := iter.First(); valid; valid = iter.Next() {
}
```

You can also do:

```
for valid := iter.SeekGE(key); valid; valid = iter.Next() {
}
```

This loop (which you provided above) appears broken to me:

```
	for {
		if !iter.SeekGE(key) {
			break
		}
		if !iter.Next() {
			break
		}
	}
```

On every iteration, you're seeking to `key`. If the `SeekGE` call returns true and the subsequent `Next` call returns true, that loop will never terminate.

**Comment by petermattis** [comment]
Also note that your original code was almost correct. You wrote:

```
        iter := db.NewIter(&pebble.IterOptions{LowerBound: []byte("kek")})
	for succ := iter.Next(); succ == true; succ = iter.Next() {
		val := iter.Value()
	}
```

The problem with this is that an iterator starts as invalid/unpositioned and a call to `Next` does not change that. A small tweak would have allowed that to work:

```
        iter := db.NewIter(&pebble.IterOptions{LowerBound: []byte("kek")})
	for succ := iter.First(); succ == true; succ = iter.Next() {
		val := iter.Value()
	}
```

Lastly, `{Lower,Upper}Bound` are primarily to prevent iteration past a certain key. Specifying `LowerBound` when all you are doing is iterating forward is equivalent to:

```
        iter := db.NewIter(nil})
	for succ := iter.SeekGE([]byte("kek")); succ == true; succ = iter.Next() {
		val := iter.Value()
	}
```

By "equivalent", I mean that internally the `First` call is transformed into a `SeekGE` when `LowerBound` is not nil.

**Comment by postables** [comment]
Interesting, I'll try your suggestions and report back. As for why the `for {}` loop appears broken, that is my mistake, I omitted some code which would definitely make it not work.

This is the full code:

```Golang
// Query is used to search a datastore for keys, and optionally values
// matching a given query
func (d *Datastore) Query(q query.Query) (query.Results, error) {
	var (
		entries []query.Entry
		snap    = d.db.NewSnapshot()
		iter    *pebble.Iterator
	)
	defer snap.Close()
	if q.Prefix == "" {
		iter = snap.NewIter(nil)
	} else {
		iter = snap.NewIter(&pebble.IterOptions{LowerBound: []byte(q.Prefix)})
	}
	defer iter.Close()
	// get the very first result
	if !iter.First() {
		return nil, errors.New("no results found")
	}
	entry := query.Entry{}
	key := iter.Key()
	entry.Key = string(key)
	if !q.KeysOnly {
		entry.Value = iter.Value()
	}
	entries = append(entries, entry)
	for {
		if !iter.SeekGE(key) {
			break
		}
		if !iter.Next() {
			break
		}
		entry = query.Entry{}
		key = iter.Key()
		entry.Key = string(key)
		if !q.KeysOnly {
			entry.Value = iter.Value()
		}
		entries = append(entries, entry)
	}
	results := query.ResultsWithEntries(q, entries)
	return results, nil
}
```

Let me try your suggestions and I'll report back. Thanks for the prompt response!

**Comment by postables** [comment]
Your suggestion worked! Excellent, thank you very much this is a lot cleaner and easier to reason about.

Sort of a "side question" but I was wondering when you expect this to be "recomended" for usage? I'll close the issue since it is now resolved. Much appreciated for the quick response :)

**Comment by petermattis** [comment]
Seeing the full code, I think your loop should be:

```
iter := snap.NewIter(nil)
for valid := iter.SeekGE([]byte(q.Prefix)); valid; valid = iter.Next() {
}
```

Unless you're doing something unusual with the comparator, the prefix `""` should be the first key in the database.

**Comment by petermattis** [comment]
> Sort of a "side question" but I was wondering when you expect this to be "recomended" for usage? I'll close the issue since it is now resolved. Much appreciated for the quick response :)

There is one serious performance deficiency being worked on (#7) and there is still a lot of correctness testing to be done. So probably several months depending on how much time we find to work on it. I'd be interested in hearing a report on your experience, both good and bad. Definitely file bugs if you suspect correctness issues.

**Comment by postables** [comment]
Sounds good! I'm looking for a solid alternative to Badger to use with IPFS, and pebble seems extremely promising so I'll be messing around with it for awhile. Will definitely report back with my overall experience.

Cheers!
