### ISSUE TITLE
perf: add AbbreviatedKey support to mergingIter

### ISSUE THREAD

**Issue by petermattis** [petermattis/pebble#17]
`mergingIter.{Next,Prev}` currently perform a full key comparison. The `AbbreviatedKey` facility used by `batchskl` could be used here as well to do a quick check on a fixed prefix of the key. An initial prototype showed this to provide a modest improvement in performance.

**Comment by petermattis** [comment]
@justinj This is probably easier than #28, and should provide a speedup when iterating over an LSM with data spread across multiple sstables.

**Comment by justinj** [comment]
Cool, will investigate!

**Comment by justinj** [comment]
Closing this given the investigation in [this comment](https://github.com/petermattis/pebble/pull/53#issuecomment-482700973).
