### ISSUE TITLE
"undefined: syscall.SyncFileRange" when compiling for armv7 processors

### ISSUE THREAD

**Issue by postables** [petermattis/pebble#171]
Trying to build a program I'm writing that uses pebble to run on my Raspberry Pi 3B+ gives me the following error:

```
# github.com/petermattis/pebble/vfs
../../../../go/pkg/mod/github.com/petermattis/pebble@v0.0.0-20190702160538-d011cead4df8/vfs/syncing_file_linux.go:39:33: undefined: syscall.SyncFileRange
../../../../go/pkg/mod/github.com/petermattis/pebble@v0.0.0-20190702160538-d011cead4df8/vfs/syncing_file_linux.go:76:9: undefined: syscall.SyncFileRange
```

**Comment by petermattis** [comment]
We probably need to add another build tag to https://github.com/petermattis/pebble/blob/master/vfs/syncing_file_linux.go#L5. And the inverse to https://github.com/petermattis/pebble/blob/master/vfs/syncing_file_generic.go#L5. Can you include the output of `go env` when building on your Raspberry Pi? Then I can give you some more specific guidance.

**Comment by postables** [comment]
Interesting wasn't aware of build tags :thinking: 

I was doing the build locally on my linux laptop via `GOOS=linux GOARCH=arm GOARM=7 go build` however here is my `go env` output:

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/solidity/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/solidity/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build412279504=/tmp/go-build -gno-record-gcc-switches"
```
