### ISSUE TITLE
sstable: shrinking block size results in mismatch SSTable

### ISSUE THREAD

**Issue by Ryanfsdf** [petermattis/pebble#192]
Shrinking the block size results in a different SST file compared to RocksDB.

What I did:
In `make-table.cc`, add `table_options.block_size = 2048;` before writing each of the tables and regenerate the test tables.

In `table_test.go:build()`, add `BlockSize: 2048` to `TableOptions`.

**Comment by petermattis** [comment]
I poked around at this a bit tonight and I my suspicion is that Pebble has slightly different heuristics for choosing the block boundaries. For the test `TestFixtureOutput/compressed=false,fullKeyFilter=false,prefixFilter=false`, a difference is reported at byte 18343. Instrumenting `sstable/Writer` to output the offsets and sizes of the data blocks I see:

```
  write raw block: 0 2041
  write raw block: 2046 2044
  write raw block: 4095 2039
  write raw block: 6139 2036
  write raw block: 8180 2032
  write raw block: 10217 2042
  write raw block: 12264 2039
  write raw block: 14308 2037
* write raw block: 16350 2044
  write raw block: 18399 2035
  write raw block: 20439 2030
  write raw block: 22474 2035
  write raw block: 24514 2036
  write raw block: 26555 237
  write index block
  write raw block: 26797 322
  write raw block: 27124 727
  write raw block: 27856 34
```

So byte 18343 is right near the end of 9th data block. The corresponding RocksDB sstable (`h.no-compression.sst`) has data blocks at:

```
  read data block: 0 2041
  read data block: 2046 2044
  read data block: 4095 2039
  read data block: 6139 2036
  read data block: 8180 2032
  read data block: 10217 2042
  read data block: 12264 2039
  read data block: 14308 2037
* read data block: 16350 2029
  read data block: 18384 2040
  read data block: 20429 2030
  read data block: 22464 2035
  read data block: 24504 2036
  read data block: 26545 249
```

So the 9th data block is 15 bytes shorter in the RocksDB generated sstable, which seems to correspond exactly to 1 entry. I'm guessing there is just a small difference in math going on.

I'll note that `rocksdb_sst_dump` wasn't useful here as I really wanted to see the structure of the sstable, not the contents. It would be useful to have a command line tool for extracting that structure from an sstable.

**Comment by petermattis** [comment]
The estimated block size calculate had a bug:

```
diff --git a/sstable/writer.go b/sstable/writer.go
index 522cdc8..ecc5926 100644
--- a/sstable/writer.go
+++ b/sstable/writer.go
@@ -308,10 +308,10 @@ func (w *Writer) maybeFlush(key InternalKey, value []byte) error {
                        return nil
                }
                newSize := size + key.Size() + len(value)
-               if w.block.nEntries&w.block.restartInterval == 0 {
+               if w.block.nEntries%w.block.restartInterval == 0 {
                        newSize += 4
                }
-               // TODO(peter): newSize += 4                              // varint for shared key bytes
+               newSize += 4                              // varint for shared prefix length
                newSize += uvarintLen(uint32(key.Size())) // varint for unshared key bytes
                newSize += uvarintLen(uint32(len(value))) // varint for value size
                if newSize <= w.blockSize {
```

Notice the `&` instead of the `%`. Gah! I stared at that code so long, unable to see the problem. I finally had to printf variables in order to catch the problem.

**Comment by petermattis** [comment]
Note that after fixing the data block size calculation, there is another discrepancy. I'm not sure if it is in the index block or the properties block.

**Comment by petermattis** [comment]
Found the second discrepancy. I had failed to set the RocksDB shortening mode to `kShortenSeparatorsAndSuccessor` which was causing the last entry in the index to not be shortened.
