### ISSUE TITLE
cmd/pebble: convert into a debugging/analysis tool

### ISSUE THREAD

**Issue by petermattis** [petermattis/pebble#202]
The `pebble` tool currently has a handful of benchmarking commands. I think we should move those benchmarks (essentially the whole `pebble` tool) to `internal/pbench` and reserve the `pebble` tool for debugging/analysis commands. This would be similar to a combination of the RocksDB `ldb` and `sst_dump` tools. Some debugging commands that we definitely want:

* `ldb dump_wal` - output the contents of a WAL file
* `ldb dump_manifest` - output the contents of a MANIFEST file
* `sst_dump --show_properties` - show the properties in an sstable
* `sst_dump --command=check|scan|verify` - check/scan/verify the contents of an sstable

I'd also like a tool for showing the structure and metadata of an sstable (block offsets and sizes, properties, etc).

Similar to the way this is structured in RocksDB, these diagnostic commands should be a library (in addition to a standalone tool) so that we can easily link them into the CockroachDB binary.

@ajkr Are there other debugging commands that you've found useful in the past?

**Comment by ajkr** [comment]
I've been using RocksDB's `ldb` and `sst_dump` on Pebble DBs and it's been working well.

Another useful one we had was Python bindings. Or if there's a REPL that we can use to call Go functions that'd work well too. It's really a lot easier to manipulate a DB one step at a time, watching how it changes, than it is to write a big unit test to expose some complicated edge case. I found this helpful for debugging although my teammates didn't use it.

**Comment by petermattis** [comment]
Another useful dump is to print the level structure:

```
level__files____size___score______in__ingest____move____read___write___w-amp
  WAL      0     0 B       -     0 B       -       -       -    16 G     0.0
    0     20   7.8 G   71.10    16 G     0 B     0 B    24 G    40 G     2.5
    1      0     0 B    0.00     0 B     0 B     0 B     0 B     0 B     0.0
    2      0     0 B    0.00     0 B     0 B     0 B     0 B     0 B     0.0
    3      0     0 B    0.00     0 B     0 B     0 B     0 B     0 B     0.0
    4      0     0 B    0.00     0 B     0 B     0 B     0 B     0 B     0.0
    5   1787   7.1 G    0.00   7.8 G     0 B     0 B    24 G    24 G     3.1
    6    197   787 M    0.00   819 M     0 B     0 B   1.7 G   1.7 G     2.1
total   2004    16 G    0.00    16 G     0 B     0 B    50 G    82 G     5.1
```
