### ISSUE TITLE
sstable: check comparer and merger on table open

### ISSUE THREAD

**Issue by petermattis** [petermattis/pebble#208]
The sstable properties contain both the name of the comparer and the name of the merger that were configured at the time the sstable was built. Neither are currently checked for consistency when an sstable is opened for reading. Both should be.

RocksDB doesn't seem to check these properties. @ajkr Is this just an oversight in RocksDB?

**Comment by ajkr** [comment]
I am not sure. I cannot think of what else the comparator and merge operator would be useful for in the table properties, so probably an oversight. Although, I think it already checks the comparator / merge operator names haven't changed when the DB is reopened via the OPTIONS file. That should achieve the same result (ignoring ingested files), I guess.

**Comment by petermattis** [comment]
I think the main place this would show utility is in sstable debugging tools. For example, #205. In that case, there is no `OPTIONS` file to check against.

**Comment by ajkr** [comment]
Oh got it. Yeah I agree it is a good check to have there.

**Comment by petermattis** [comment]
The verification was added in #205, but this still needs to be tested.
