### ISSUE TITLE
Production ETA

### ISSUE THREAD

**Issue by olekukonko** [petermattis/pebble#233]
When do you think 

- This will be `production-ready` 
- This can be part of the `cockrockdb`

Thanks

**Comment by petermattis** [comment]
> This can be part of the cockrockdb

The current plan is to allow Pebble as an option in the Spring 2020 release of CockroachDB. 

> This will be production-ready

By Spring 2020 for sure (see above). Likely some time before that as additional testing is done and our comfort level increases.

**Comment by olekukonko** [comment]
@petermattis  thanks for the prompt response. Am definitely an early adopter.  Regards.

**Comment by petermattis** [comment]
@olekukonko Glad to hear that.

**Comment by olekukonko** [comment]
@petermattis am back to check on progress?  How promising has this been compared to rocksdb ?

**Comment by petermattis** [comment]
@olekukonko Pebble should be usable as a drop-in replacement for RocksDB for the areas of functional overlap. It is compatible with the on-disk RocksDB formats. If you're using Pebble for a brand new system you should have no concerns. Pebble's performance is on-par or better than RocksDB (write performance is on-par, read performance is somewhat better). I expect the performance differences to increase over time.

I'd feel comfortable using Pebble in a production setting now, though note we haven't done so in CRDB yet. We're planning to start that testing in the next few weeks.

**Comment by olekukonko** [comment]
I am excited already. I have waited for a year so I can wait for `next few weeks.` It's worth the wait.  We will definitely be assisting in testing and file bugs if we find any. 

Well done @petermattis you have done an excellent job here.
