### ISSUE TITLE
perf: investigate concurrent flushes

### ISSUE THREAD

**Issue by petermattis** [petermattis/pebble#46]
Pebble only allows a single flush of a memtable to L0 to occur at any time. RocksDB allows multiple concurrent flushes, though note that the resulting sstables need to be installed ["in order".](https://github.com/facebook/rocksdb/blob/4fc442029a0c69edf3ae5293ffcc8cd8a1235813/db/memtable_list.cc#L355-L362) The benefit of allowing multiple concurrent flushes is a bit unclear, as on the surface allowing a concurrent flush would seem to simply divide write bandwidth across the concurrent flushes.

Cc @ajkr

**Comment by petermattis** [comment]
@ajkr Do you have any additional insight as to the benefit of concurrent flushes? The same criticisms I have for [concurrent compactions](https://github.com/petermattis/pebble/issues/47) apply here, but more so as we're not talking about compactions at different levels. I suppose if flushes are CPU limited, concurrent flushes will allow more throughput, but I haven't seen any evidence of flushes being CPU limited. Concurrent flushes would have the side effect of consuming more CPU and thus slowing down the rate at which memtables are filling, but I think other more direct mechanisms to adjust the pace of user writes would be preferable. Is there anything I'm missing here?

**Comment by ajkr** [comment]
Right I think that's the idea - it can help if flushes are CPU bound by parallelizing the work. If they're not CPU bound, or the memtable fill rate is slower than the flush rate, seems it wouldn't help. I can't recall any specific cases where it helped, though it's been baked into RocksDB forever so it's hard to know who is benefiting from it.

**Comment by petermattis** [comment]
Ok. I'm going to close this issue as I suspect it isn't worthwhile and I can't see us investigating it further any time soon. Concurrent compactions are a different matter which still requires investigation.
