### ISSUE TITLE
compaction: support CompactionFilter

### ISSUE THREAD

**Issue by chrislusf** [petermattis/pebble#54]
I am migrating code from gorocksdb to pebble.

Ideally CompactionFilter can be added to skip some entry by key or value. The CompactionFilter is defined as this:

https://github.com/tecbot/gorocksdb/blob/master/compaction_filter.go#L7

**Comment by vtolstov** [comment]
@chrislusf do you plan to use this package in seaweedfs ?

**Comment by petermattis** [comment]
Hi @chrislusf, please note this line from the `README`:

> Pebble intentionally does not aspire to include every feature in RocksDB and is specifically targeting the use case and feature set needed by CockroachDB.

The rationale behind this statement is to keep the Pebble feature set small and manageable. I can see the value in a full-featured LSM that has all of the bells and whistles of RocksDB. Pebble is not that project. I fully support you creating a new project, derived from Pebble, with that goal.

**Comment by chrislusf** [comment]
> @chrislusf do you plan to use this package in seaweedfs ?

plan to use it in https://github.com/chrislusf/vasto

**Comment by chrislusf** [comment]
> Hi @chrislusf, please note this line from the `README`:
> 
> > Pebble intentionally does not aspire to include every feature in RocksDB and is specifically targeting the use case and feature set needed by CockroachDB.
> 
> The rationale behind this statement is to keep the Pebble feature set small and manageable. I can see the value in a full-featured LSM that has all of the bells and whistles of RocksDB. Pebble is not that project. I fully support you creating a new project, derived from Pebble, with that goal.

Thanks for your reply! Seems this is the only one aiming for a go-version RocksDB as of now. Would be good to know other similar projects if you know any.

**Comment by petermattis** [comment]
> Thanks for your reply! Seems this is the only one aiming for a go-version RocksDB as of now. Would be good to know other similar projects if you know any.

Pebble is not a Go version of RocksDB. It is inspired by RocksDB, and aims to be compatible where there is feature overlap, but that is the extent of the compatibility. I'm not aware of any other project which aims to be a Go version of RocksDB.

**Comment by vtolstov** [comment]
@chrislusf thanks
