### ISSUE TITLE
Have you considered WiscKey ?

### ISSUE THREAD

**Issue by olekukonko** [petermattis/pebble#63]
Have you considered separates keys from values ie. [WiscKey](https://www.usenix.org/system/files/conference/fast16/fast16-papers-lu.pdf) just like Badger and TiDB?

**Comment by petermattis** [comment]
Pebble aims to be RocksDB compatible (at least initially). RocksDB does have something WiscKey-like in the [`blob_db`](https://github.com/facebook/rocksdb/tree/master/utilities/blob_db) utility, but I haven't looked at the implementation closely enough to know if it is worth following. Also the `blob_db` implementation is incomplete at the moment, notably missing GC support.

**Comment by olekukonko** [comment]
@petermattis thanks for the response ... will keep a close eye on this project.
