### ISSUE TITLE
db: check merger name on startup

### ISSUE THREAD

**Issue by petermattis** [petermattis/pebble#84]
The `db.Merger.Name` field has a comment that is current unimplemented:

	// Pebble stores the merger name on disk, and opening a database with a
	// different merger from the one it was created with will result in an error.

The merger name is stored in the sstable `rocksdb.merge.operator` property, but we don't seem to check it anywhere currently. Need to check how RocksDB handles this and do something similar.

**Comment by petermattis** [comment]
Well, apparently RocksDB doesn't do anything with the name either:

>  // TODO: the name is currently not stored persistently and thus
  //       no checking is enforced. Client is responsible for providing
  //       consistent MergeOperator between DB opens.

The above isn't completely true as the name is persisted to the sstable `rocksdb.merge.operator` property. I looked, but couldn't find anywhere that the merge operator name is verified (so at least part of the TODO is accurate).

Cc @ajkr

**Comment by ajkr** [comment]
It's supposed to verify `MergeOperator::Name()` was unchanged when you load from options file: https://github.com/facebook/rocksdb/blob/a7d103198ee27fbd3f9146e57355ea02eb10836d/options/options_helper.cc#L1969. Although I just tested it out and it did not fail when I changed the name.
