### ISSUE TITLE
perf: skip user-key comparisons if prev seqnum is zero

### ISSUE THREAD

**Issue by petermattis** [petermattis/pebble#87]
`db.Iterator.Next` currently performs a comparison of the user-key when iterating to the next entry. This comparison can be elided if the previous seqnum is zero. In Pebble this is currently rarely the case, but RocksDB contains an optimization to set the seqnum to zero for records stored in the bottommost level (modulo snapshot requirements).

A quick test shows that skipping the user-key comparison provides a ~5% speedup when iterating over sstables in the bottommost level.

**Comment by petermattis** [comment]
RocksDB accomplishes the seqnum zeroing in the `CompactionIter`:

```
  // Zeroing out the sequence number leads to better compression.
  // If this is the bottommost level (no files in lower levels)
  // and the earliest snapshot is larger than this seqno
  // and the userkey differs from the last userkey in compaction
  // then we can squash the seqno to zero.
  //
  // This is safe for TransactionDB write-conflict checking since transactions
  // only care about sequence number larger than any active snapshots.
  //
  // Can we do the same for levels above bottom level as long as
  // KeyNotExistsBeyondOutputLevel() return true?
  if ((compaction_ != nullptr && !compaction_->allow_ingest_behind()) &&
      ikeyNotNeededForIncrementalSnapshot() && bottommost_level_ && valid_ &&
      IN_EARLIEST_SNAPSHOT(ikey_.sequence) && ikey_.type != kTypeMerge) {
    assert(ikey_.type != kTypeDeletion && ikey_.type != kTypeSingleDeletion);
    ikey_.sequence = 0;
    current_key_.UpdateInternalKey(0, ikey_.type);
  }
```

This code is called at the very end of `CompactionIter::Next`. Two bits that I'm still puzzling about:
* The comment says `and the userkey differs from the last userkey in compaction`, but I don't see where that check is being made.
* Why is seqnum zeroing not performed for merge operations (i.e. what is the `ikey_.type != kTypeMerge` condition for)?

@ajkr?

**Comment by ajkr** [comment]
> - The comment says and the userkey differs from the last userkey in compaction, but I don't see where that check is being made.

I think that comment is outdated. I recall working with a bootcamper to remove that check. Here it is: https://github.com/facebook/rocksdb/commit/59244447e3123da87fc3f3ade859d85f69165f40

**Comment by ajkr** [comment]
> - Why is seqnum zeroing not performed for merge operations (i.e. what is the ikey_.type != kTypeMerge condition for)?

I am not sure. I think typically a merge would be converted to a `Put` when it's compacted to the bottom level. It should always be eligible for `FullMerge` in that case because the base value will always be available. I could try making that an assert to verify my theory if it's of interest to you.

**Comment by petermattis** [comment]
> I am not sure. I think typically a merge would be converted to a Put when it's compacted to the bottom level. It should always be eligible for FullMerge in that case because the base value will always be available. I could try making that an assert to verify my theory if it's of interest to you.

That theory sounds right to me. Yes, it is of interest to verify it. 

Thanks for the quick responses.
